/**
 * Chess960 (Fischer Random Chess) Setup Generator
 * Generates valid random starting positions following Chess960 rules:
 * 1. Bishops must be on opposite-colored squares
 * 2. King must be between the two Rooks
 * 3. All pieces start on rank 1/8 (white/black respectively)
 */

import { COLORS } from './constants';

const PIECES = {
  ROOK: 'R',
  KNIGHT: 'N',
  BISHOP: 'B',
  QUEEN: 'Q',
  KING: 'K'
};

/**
 * Generate a single valid Chess960 starting position
 * Returns array of 8 pieces for one color
 */
export const generateChess960Setup = () => {
  const setup = new Array(8).fill(null);
  
  // Step 1: Place Bishops on opposite colors
  // Light-squared bishop (even indices: 0,2,4,6)
  const lightBishopPos = [0, 2, 4, 6][Math.floor(Math.random() * 4)];
  setup[lightBishopPos] = PIECES.BISHOP;
  
  // Dark-squared bishop (odd indices: 1,3,5,7)
  const darkBishopPos = [1, 3, 5, 7][Math.floor(Math.random() * 4)];
  setup[darkBishopPos] = PIECES.BISHOP;
  
  // Step 2: Place Queen on random empty square
  const emptyForQueen = setup.map((p, i) => p === null ? i : -1).filter(i => i !== -1);
  const queenPos = emptyForQueen[Math.floor(Math.random() * emptyForQueen.length)];
  setup[queenPos] = PIECES.QUEEN;
  
  // Step 3: Place Knights on remaining empty squares
  const emptyForKnights = setup.map((p, i) => p === null ? i : -1).filter(i => i !== -1);
  const knight1Index = Math.floor(Math.random() * emptyForKnights.length);
  const knight1Pos = emptyForKnights[knight1Index];
  setup[knight1Pos] = PIECES.KNIGHT;
  
  emptyForKnights.splice(knight1Index, 1);
  const knight2Pos = emptyForKnights[Math.floor(Math.random() * emptyForKnights.length)];
  setup[knight2Pos] = PIECES.KNIGHT;
  
  // Step 4: Place King and Rooks in remaining 3 squares
  // King must be between the Rooks
  const emptyForKingRooks = setup.map((p, i) => p === null ? i : -1).filter(i => i !== -1);
  // Choose middle position for King
  const kingIndex = 1; // Middle of the 3 remaining positions
  const kingPos = emptyForKingRooks[kingIndex];
  setup[kingPos] = PIECES.KING;
  
  // Rooks go on the remaining two positions
  const rookPositions = [emptyForKingRooks[0], emptyForKingRooks[2]];
  setup[rookPositions[0]] = PIECES.ROOK;
  setup[rookPositions[1]] = PIECES.ROOK;
  
  return setup;
};

/**
 * Create initial board with Chess960 setup
 * Returns 8x8 board array
 */
export const createChess960Board = () => {
  const whiteSetup = generateChess960Setup();
  const blackSetup = [...whiteSetup]; // Mirror for black
  
  const board = Array(8).fill(null).map(() => Array(8).fill(null));
  
  // Place white pieces (rank 7, index 7)
  whiteSetup.forEach((piece, col) => {
    board[7][col] = COLORS.WHITE + piece;
  });
  
  // Place white pawns (rank 6, index 6)
  for (let col = 0; col < 8; col++) {
    board[6][col] = COLORS.WHITE + 'P';
  }
  
  // Place black pieces (rank 0)
  blackSetup.forEach((piece, col) => {
    board[0][col] = COLORS.BLACK + piece;
  });
  
  // Place black pawns (rank 1, index 1)
  for (let col = 0; col < 8; col++) {
    board[1][col] = COLORS.BLACK + 'P';
  }
  
  return board;
};

/**
 * Get all 960 valid starting positions
 * This is pre-computed for reference/validation
 */
export const getAllChess960Positions = () => {
  // There are exactly 960 valid positions
  // Generated by: 4 bishop positions × 6 queen positions × 10 knight positions × 1 king-rook arrangement
  // = 4 × 6 × 10 × 4 = 960
  
  const positions = [];
  const seen = new Set();
  
  // Generate until we have all 960
  while (positions.length < 960) {
    const setup = generateChess960Setup();
    const key = setup.join('');
    
    if (!seen.has(key)) {
      seen.add(key);
      positions.push(setup);
    }
  }
  
  return positions;
};

/**
 * Validate if a setup is a valid Chess960 position
 */
export const isValidChess960Setup = (setup) => {
  if (!Array.isArray(setup) || setup.length !== 8) return false;
  
  // Check all required pieces are present
  const pieceCount = {};
  setup.forEach(p => {
    pieceCount[p] = (pieceCount[p] || 0) + 1;
  });
  
  if (pieceCount[PIECES.KING] !== 1) return false;
  if (pieceCount[PIECES.QUEEN] !== 1) return false;
  if (pieceCount[PIECES.ROOK] !== 2) return false;
  if (pieceCount[PIECES.BISHOP] !== 2) return false;
  if (pieceCount[PIECES.KNIGHT] !== 2) return false;
  
  // Check bishops on opposite colors
  const bishopIndices = setup.map((p, i) => p === PIECES.BISHOP ? i : -1).filter(i => i !== -1);
  if (bishopIndices.length !== 2) return false;
  if ((bishopIndices[0] % 2) === (bishopIndices[1] % 2)) return false;
  
  // Check King is between Rooks
  const rookIndices = setup.map((p, i) => p === PIECES.ROOK ? i : -1).filter(i => i !== -1);
  const kingIndex = setup.indexOf(PIECES.KING);
  if (kingIndex <= Math.min(...rookIndices) || kingIndex >= Math.max(...rookIndices)) return false;
  
  return true;
};

/**
 * Convert setup array to FEN-compatible castling rights string
 */
export const getChess960CastlingRights = (setup) => {
  const kingCol = setup.indexOf(PIECES.KING);
  const rookCols = setup.map((p, i) => p === PIECES.ROOK ? i : -1).filter(i => i !== -1);
  
  // In Chess960, castling rights are denoted by the rook's file
  const files = 'abcdefgh';
  const kingsideRook = Math.max(...rookCols);
  const queensideRook = Math.min(...rookCols);
  
  return {
    white: {
      kingside: files[kingsideRook].toUpperCase(),
      queenside: files[queensideRook].toUpperCase()
    },
    black: {
      kingside: files[kingsideRook],
      queenside: files[queensideRook]
    }
  };
};

export default {
  generateChess960Setup,
  createChess960Board,
  getAllChess960Positions,
  isValidChess960Setup,
  getChess960CastlingRights
};
